name: renewable_power_plants

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.5
  - bokeh=0.12.2
  - notebook  # jupyter notebook
  - numpy=1.17.4
  - pandas=0.25.3
  - pyyaml=5.2
  - requests=2.20.0
  - sqlalchemy=1.3.11
  - xlrd=1.2.0
  - xlsxwriter=1.2.8
  - pip:
    - utm==0.4.1
  - bs4=4.8.1
  - fake_useragent
  - bng_to_latlon
  - matplotlib=3.1.2
  - cartopy=0.17.0
  - geopandas=0.6.2
  - shapely=1.6.4post2
  - fiona=1.8.13

